### ISSUE TITLE
"ReferenceError: You are trying to `import` a file after the Jest environment has been torn down." when run `yarn test`

### ISSUE THREAD

**Issue by geoseong** [dooboolab/hackatalk#122]
**Describe the bug**
I want to say that this is not a `hackatalk-mobile`'s own bug,
just want to discuss why this happens and how can resolve this.

I commited to [PR#115](https://github.com/dooboolab/hackatalk-mobile/pull/115) and didn't pass in `ci/circleci: node` section. **(I attached detailed error message down below at `Expected behavior` section)**

I feel strange and so I tried to run `yarn test` in my local workspace, and I found same error message.

weird thing is that I haven't seen this error before I push my commits to [PR](https://github.com/dooboolab/hackatalk-mobile/pull/115).

and I googled it, I found this [issues in jest repo](https://github.com/facebook/jest/issues/6434#issuecomment-525576660)

so I put `jest.useFakeTimers()` in following test codes that kinds of error happens, and error disappeared.
(can see codes in [0b77338](https://github.com/dooboolab/hackatalk-mobile/pull/115/commits/0b77338ea5cfc3f08c283a8025cd41d428c748bf))

- src/components/screen/__tests__/ProfileUpdate.test.tsx
- src/components/screen/__tests__/WebView.test.tsx
- src/components/shared/__tests__/ErrorView.test.tsx
- src/components/shared/__tests__/GiftedChat.test.tsx
- src/components/shared/__tests__/UserListItem.test.tsx

I've seen `ci/circleci: node`'s Jest test terminal contexts in other PRs (for example, [can see this](https://circleci.com/gh/dooboolab/hackatalk-mobile/567?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), I could see this kind of error exist.

but the reason it can pass the test is, it processed within 30000ms.
Unfortunately my test case doesn't make it passed within 30000ms.

**To Reproduce**
remove `jest.useFakeTimers()` in test code

**Expected behavior**
You'll see the error like this below

```sh
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at parseErrorStack (node_modules/react-native/Libraries/Core/Devtools/parseErrorStack.js:27:28)
      at createStack (node_modules/react-native/Libraries/YellowBox/Data/YellowBoxWarning.js:110:10)
      at Function.parse (node_modules/react-native/Libraries/YellowBox/Data/YellowBoxWarning.js:39:14)
      at Object.add (node_modules/react-native/Libraries/YellowBox/Data/YellowBoxRegistry.js:80:57)
      at registerWarning (node_modules/react-native/Libraries/YellowBox/YellowBox.js:138:23)
 FAIL  src/components/screen/__tests__/ChangePw.test.tsx
  ● [ChangePw] screen › interactions › should simulate textChanged

    TypeError: stacktraceParser.parse is not a function
```

If you have some idea to resolve this error or have some opinion or advice, please let me know in the comments.

**Comment by mym0404** [comment]
In my own project, there are the same warnings in jest.
But that doesn't occur an error in my project.
In some case, I could resolve warning with `await wait(() => Promise.resolve());` at the end of the test.
It seems to asynchronize operation malfunctioning.

![image](https://user-images.githubusercontent.com/33388801/82905670-1d650e80-9f9f-11ea-81dc-62f39a59abac.png)

![image](https://user-images.githubusercontent.com/33388801/82905692-22c25900-9f9f-11ea-8579-188251466f83.png)

**Comment by hyochan** [comment]
Yeah, we have some bad testings written currently. Looking forward to resolving this while integrating a relay.
