### ISSUE TITLE
Need feedback: add project's diagram to wiki or code

### ISSUE THREAD

**Issue by geoseong** [dooboolab/hackatalk#169]
I'm drawing diagrams of hackatalk's client and server using VSCode's [drawio extension](https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio) which is great!.

here is my work in [my fork repository's wiki page](https://github.com/geoseong/hackatalk/wiki).

the reason why I did this is to understand the project's structure.

and if my diagrams might help people who are interested in this project, I'm about to put this content here.

but need to decide which place would be proper.

**into Code**

If I put this content into Code, I'm planning to make new `diagrams` directory and put diagrams in it.
It needs to do Pull Request when the diagram changed due to changing project structure.

**into Wiki**

put the diagrams into the Wiki page to make the diagrams change easier.
can decorate in some ways like documentation page.

so please let me know you guys opinion.

**Comment by JongtaekChoi** [comment]
I think the second one is better.

**Comment by hyochan** [comment]
Vote for 2 either.

**Comment by daadaadaah** [comment]
I vote for 2!!

Your diagrams are very awesome.👍👍👍

**Comment by geoseong** [comment]
@hyochan okay I go for option 2 to wiki.

but I don't have write access to this repository so I can't access the Wiki page.

please consider referring to this document -> [Changing access permissions for wikis](https://docs.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis)

**Comment by hyochan** [comment]
<img width="437" alt="Screen Shot 2020-07-24 at 3 23 04 AM" src="https://user-images.githubusercontent.com/27461460/88323322-06535a80-cd5d-11ea-9186-6e41220dc198.png">

@geoseong Can you check now?

**Comment by geoseong** [comment]
@hyochan I cannot access to `Settings`

![image](https://user-images.githubusercontent.com/19166187/88361107-f0708480-cdb2-11ea-926a-1bffd44d047d.png)

**Comment by hyochan** [comment]
> @hyochan I cannot access to `Settings`
> 
> ![image](https://user-images.githubusercontent.com/19166187/88361107-f0708480-cdb2-11ea-926a-1bffd44d047d.png)

I've done `Changing access permissions for wikis` as shown above. Is there more I should do?

**Comment by geoseong** [comment]
@hyochan thanks, now I can access Wiki page and edit.

but I cannot push commits via CLI like below. I think I don't have enough permission to access. maybe this is related to access `Settings` page.
```
$ git push origin master
remote: Permission to dooboolab/hackatalk.wiki.git denied to geoseong.
fatal: unable to access 'https://github.com/dooboolab/hackatalk.wiki.git/': The requested URL returned error: 403
```

but It's okay to edit wiki page on github page. thanks!

**Comment by hyochan** [comment]
> @hyochan thanks, now I can access Wiki page and edit.
> 
> but I cannot push commits via CLI like below. I think I don't have enough permission to access. maybe this is related to access `Settings` page.
> 
> ```
> $ git push origin master
> remote: Permission to dooboolab/hackatalk.wiki.git denied to geoseong.
> fatal: unable to access 'https://github.com/dooboolab/hackatalk.wiki.git/': The requested URL returned error: 403
> ```
> 
> but It's okay to edit wiki page on github page. thanks!

I think you should give a `Pull request` instead.

**Comment by geoseong** [comment]
there's no Pull request workflow for Wiki repository.

should we follow the [`Taffy` workflow posted on stackoverflow](https://stackoverflow.com/a/11481887/8026431)?

**Wiki merge workflow**
1. Manually create a fork of the `hackatalk` wiki repo
```
git clone https://github.com/dooboolab/hackatalk.wiki.git
```
2. Remove the original "origin" remote and add your github repo as new "origin"
> If you don't have any wiki content, you should create any page in your wiki.
```
git remote rm origin
git remote add origin https://github.com/<YOUR_USERNAME>/hackatalk.wiki.git
```
3. Make your proposed changes locally, then push them to your github account
```
git push -u origin master ('-u origin master' only required the first time; afterwards just do git push)
```
4. Submit the issue to review your changes and merge the changed wiki contents in.
- include a link to your wiki repo and describe what you've changed.

or we will go to the first option `into Code`.

**Comment by hyochan** [comment]
Thanks for the link. I think we need another repository to manage the `WIKI` in that case. Furthermore, I think we have another better option to handle the document. How about contributing to [hackatalk-website](https://github.com/dooboolab/hackatalk-website) which is hosted in [website.hackatalk.dev](http://website.hackatalk.dev/).

**Comment by geoseong** [comment]
actually I'd considered contributing [hackatalk-website](https://github.com/dooboolab/hackatalk-website) for the first time and it's time to do it lol. okay let me do it

**Comment by hyochan** [comment]
Let me manage it first since this is too old! Then I will come back to you~

**Comment by hyochan** [comment]
@geoseong I've structured documents so that you can only add to that instead of thinking of how to manage the documents.
