### ISSUE TITLE
Security vulunerablities in verification mail logic

### ISSUE THREAD

**Issue by LiteHell** [dooboolab/hackatalk#180]
There's a vulunerablility that enables us to verify email and reset password without actual verification.

On server side, Server verifies an email address by comparing real email address and bcrypt hash of it in an verification url. This logic is used in email verification and password reset logic.
It sounds simple but makes an security vulunerablility, because it enables to reset password or verify email without actual email verification.
We can make bcrypt hash with only email address. That means verification email actually not needed to verify email.
Using this vulunerablility, we can verify email address and reset password without verification.

**Comment by hyochan** [comment]
Thanks for coming up with the issue. Do you have any proposal that can improve your concern?

**Comment by LiteHell** [comment]
> 
> 
> Thanks for coming up with the issue. Do you have any proposal that can improve your concern?

I'm thinking of using jwt, created for email verification, instead of bcrypt-ed email address. I wrote code fixes on [my forked repository](https://github.com/LiteHell/hackatalk/tree/fix/emailVerification), but not tested yet.
I'll create PR for this as soon as possible.
