### ISSUE TITLE
replace bcrypt-nodejs with bcrypt

### ISSUE THREAD

**Issue by neverlish** [dooboolab/hackatalk#190]
**Specify project**
- server side issue

**Is your feature request related to a problem? Please describe.**
- In hackatalk project, npm bcrypt-nodejs is being used. [npm bcrypt-nodejs](https://www.npmjs.com/package/bcrypt-nodejs) says as following
```
bcrypt-nodejs is no longer actively maintained. Please use bcrypt or bcryptjs. See https://github.com/kelektiv/node.bcrypt.js/wiki/bcrypt-vs-brypt.js to learn more about these two options
```
So i suggest to replace bcrypt-nodejs with ~bcryptjs~ [bcrypt](https://github.com/kelektiv/node.bcrypt.js)

**Describe the solution you'd like**
write codes in below sequence, so make sure changes does not affect products.
1. write test codes for function `encryptCredential` and `validateCredential` in server/src/utils/auth.ts
2. replace bcrypt-nodejs with ~bcryptjs~ bcrypt

**Describe alternatives you've considered**
use alternative npm

**Comment by hyochan** [comment]
Sounds awesome!

**Comment by neverlish** [comment]
> Sounds awesome! However, I think we need to change to `bcrypt` instead of `bcrypt-js` since this doesn't seem to be maintained (last published 4years ago).

I agree :) I changed title and content of issue
