### ISSUE TITLE
'CONTRIBUTING.md' file has broken link.

### ISSUE THREAD

**Issue by JongtaekChoi** [dooboolab/hackatalk#195]
**Specify project**
Document issue.

**Describe the issue**
Below CONTRIBUTING ~~GUILDE~~GUIDE link was broken.
![image](https://user-images.githubusercontent.com/17980230/90097202-588e0700-dd70-11ea-81ae-aaa08eef2bbf.png)

I'm not sure if it's ok to get rid of this.

**Comment by hyochan** [comment]
This should be https://github.com/dooboolab/hackatalk/blob/master/CONTRIBUTING.md

**Comment by hyochan** [comment]
@JongtaekChoi Sorry actually you can remove this.
