### ISSUE TITLE
SendGrid Email Address Is Hard-Coded

### ISSUE THREAD

**Issue by 0916dhkim** [dooboolab/hackatalk#197]
**Specify project**
Is this `Client` issue or `Server` side issue?
This is a server-side issue.

**Is your feature request related to a problem? Please describe.**
"From" address of the outbound SendGrid message is hard-coded here:
https://github.com/dooboolab/hackatalk/blob/5d3b4e6ff29d692694fc71284c6f3a32bae61975/server/src/types/resolvers/User/mutation.ts#L282

**Describe the solution you'd like**
It would be nice to allow developers to use their own SendGrid API key. Currently, there is no way to send a verification email when testing locally without a SendGrid sender identity with "hackatalk.dev" domain. Attempt to use any other domain for a sender identity would result in 403 Forbidden status.

**Describe alternatives you've considered**
An easy way to setup local testing environment is desirable, but I think it is not okay to share an API key of "hackatalk.dev" domain publicly, as it has potential to be abused.

My best proposal is to add `SENDGRID_EMAIL` or `SENDGRID_DOMAIN` environment variable, so that emails can be sent from `noreply@<SENDGRID_DOMAIN>`. Developers would need to buy a domain & sign up for SendGrid themselves if we choose to do it this way.

I'm open to discuss alternatives here because I don't think my proposal is any better than the current state of the project.

**Comment by hyochan** [comment]
Sounds great~! I think you can give a `PR` for adding that.

**Comment by 0916dhkim** [comment]
Thank you, I will start working on this issue.
