### ISSUE TITLE
Update Button in the Profile Page Not Working

### ISSUE THREAD

**Issue by 0916dhkim** [dooboolab/hackatalk#210]
**Specify project**
Client

**Describe the bug**
"Update" button inside the profile page does nothing.

**To Reproduce**
1. Open Hackatalk.
2. Sign in.
3. Press profile icon on the top left corner.
4. Modify profile info.
5. Press the update button.

**Expected behavior**
- Profile gets updated.
- A message is shown on screen that the profile update was successful, or an error message if there was an error.

**Screenshots**
![profile](https://user-images.githubusercontent.com/8978815/90478789-9f14a480-e168-11ea-99f7-1fbbb61b2467.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Browser: Firefox
- Version: 79.0

**Comment by hyochan** [comment]
This is currently known. We've not integrated this yet in `client`.

**Comment by 0916dhkim** [comment]
Resolved #246
