### ISSUE TITLE
ChannelCreate Not Fetching Friend List

### ISSUE THREAD

**Issue by 0916dhkim** [dooboolab/hackatalk#211]
**Specify project**
Client

**Describe the bug**
Client is not fetching friend list inside `ChannelCreate` component.
Only fake friends are present.

**To Reproduce**

1. Sign in.
2. Press CHANNEL tab.
3. Press "+" FAB.

**Expected behavior**
"Real" friends should be displayed inside `ChannelCreate` component.

**Additional context**
Fake friend list is defined here:
https://github.com/dooboolab/hackatalk/blob/32c98a64a8d9b9be892d36f1b8bfde26bed95555/client/src/components/screen/ChannelCreate.tsx#L25-L114
Which is used in component state:
https://github.com/dooboolab/hackatalk/blob/32c98a64a8d9b9be892d36f1b8bfde26bed95555/client/src/components/screen/ChannelCreate.tsx#L143
Friend list should be fetched from server via graphql query.

**Comment by hyochan** [comment]
The `integration` part is lacking since the `resolvers` are being developed too.
This is known to be left over for contribution.

Thanks for the thread though :+1:

**Comment by hyochan** [comment]
Looks like this can be closed now as of 1.2 releases.
