### ISSUE TITLE
Keyboard hides label when typing on Sign up

### ISSUE THREAD

**Issue by JaeeunAhn** [dooboolab/hackatalk#227]
**Specify project**
Client

**Describe the bug**
To type the text on name label, keyboard hides it.

**To Reproduce**

1. Go to 'Login view'.
2. Click on 'Sign Up' button.
3. Click the 'Name' textfield label to type.
4. See error.

**Expected behavior**
The view will go up and label that I'm typing should be shown above the keyboard.

**Screenshots**
<img src ="https://user-images.githubusercontent.com/49272528/91646264-4d351e00-ea88-11ea-9e46-53089404637a.png" width="300">

**Desktop (please complete the following information):**

- OS: iOS
- Browser: chrome
- Version: 10.15.4

**Smartphone (please complete the following information):**

- Device: iPhone 11 pro
- OS: iOS13.6
- Browser: safari
- Version: 11.6

**Comment by hyochan** [comment]
Thanks for bringing up this issue! This would be much better if you can scroll down to the bottom when the keyboard rises!

**Comment by hyochan** [comment]
Closes after the online sync.
