### ISSUE TITLE
Use Material-UI-like Breakpoints for Media Queries

### ISSUE THREAD

**Issue by 0916dhkim** [dooboolab/hackatalk#251]
**Specify project**
Client

**Is your feature request related to a problem? Please describe.**
Currently, `minWidth` of `tablet` and `desktop` is defined in `client/src/utils/media.ts`. Material UI project organizes these width values into "breakpoints" and put them in `theme.breakpoints`.

**Describe the solution you'd like**
Hackatalk can take the same approach and use media queries like the following:

```ts
const isTablet = useMediaQuery(theme.breakpoints.up('tablet'));
```

**Additional context**
- Read https://github.com/dooboolab/hackatalk/pull/209#event-3733017666 for previous discussion.
- [MUI Docs](https://material-ui.com/components/use-media-query/)

**Comment by hyochan** [comment]
Are you saying you want to put values inside the `theme` variable as a `breakpoints`?

**Comment by 0916dhkim** [comment]
@hyochan Here's Material UI's approach : [Breakpoints - Material-UI](https://material-ui.com/customization/breakpoints/)
They provide helper functions that return media queries which can be used inside `useMediaQuery`.
For example, `theme.breakpoints.up('sm')` will return a media query that matches screen size `sm` and larger. The following is the list of their breakpoint helper functions:
- `theme.breakpoints.up`
- `theme.breakpoints.down`
- `theme.breakpoints.only`
- `theme.breakpoints.between`
