### ISSUE TITLE
Clickable Links / URL

### ISSUE THREAD

**Issue by 0916dhkim** [dooboolab/hackatalk#434]
**Specify project**
Client

**Is your feature request related to a problem? Please describe.**
Hackatalk does not format url as links. They are plain text like other messages.
![image](https://user-images.githubusercontent.com/8978815/126855108-f9e04b07-32dd-4113-a8f2-ce76a93e886f.png)

**Describe the solution you'd like**
I would like Hackatalk to format URL texts as clickable links. Here's how this feature is implemented in Slack.
![image](https://user-images.githubusercontent.com/8978815/126855098-e2cb075e-5aa2-4d97-942b-60acfbe929a6.png)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by 0916dhkim** [comment]
Also, I just noticed that message timestamps are rendered in Korean. My browser locale was en-US.

**Comment by hyochan** [comment]
Nice one to work through!
