### ISSUE TITLE
Improve a signIn function to validate a email & password correctly

### ISSUE THREAD

**Issue by DevYuns** [dooboolab/hackatalk#436]
**Specify project**
Is this `Client` issue or `Server` side issue?

client

**Describe the bug**

When try to log in with email and password, `signIn` function can not validate email. That means if I write wrong email or make a typos, It just show a password error message. So I didn't know what's wrong whether email or password.

**To Reproduce**

1. Write a email with typos
2. Write a correct password
3. then click `signIn` button,
4. It just show me a password error message, even though I write a correct password.

**Expected behavior**

When I write a wrong email address, It should give me a email error feedback.

**Screenshots**

![image](https://user-images.githubusercontent.com/58724686/127150665-74c55e7f-2a24-4011-9bc8-ec4f4cb437c9.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hyochan** [comment]
The error message for `signIn` should not be as kind as other errors for security issues. They are going to be really useful for the attackers.
