### ISSUE TITLE
login page animation starting location issue

### ISSUE THREAD

**Issue by woosanggyu** [dooboolab/hackatalk#437]
**Specify project**
Client issue

**Describe the bug**
Different starting location for login page animation on web and mobile

**To Reproduce**

1. Go to loginPage on web
2. Go to loginPage on mobile 

**Expected behavior**

Animation starting location is different 

**Screenshots**
- web

https://user-images.githubusercontent.com/45311830/127159634-bf0a1ba5-2688-4a00-b1e3-96d31549cf4f.mov

- mobile

https://user-images.githubusercontent.com/45311830/127159653-77cc3741-f006-4fc3-addf-423afc1fc612.mov

**Desktop (please complete the following information):**

- OS: macbook
- Browser  chrome
- Version 91.0

**Smartphone (please complete the following information):**

- Device: iphone12
- OS: ios

**Additional context**

**Comment by rarira** [comment]
Might be related or not..
latest version shows strange logo icon animation like belows.

1. when logo pressed(touch)
![Simulator Screen Recording - iPhone 12 Pro - 2021-07-27 at 22 25 14](https://user-images.githubusercontent.com/8540420/127162919-fef8f1b1-aeb7-4875-a5b2-e9e6e091faf0.gif)

2. when type begins in TextInput component
![Simulator Screen Recording - iPhone 12 Pro - 2021-07-27 at 22 26 00](https://user-images.githubusercontent.com/8540420/127163448-7788a7d1-a0b3-46ce-a3c7-fc2b5279e122.gif)

It happens only after the [commit](https://github.com/dooboolab/hackatalk/pull/431/commits/331b7cdd770e60b68d52955a0a4d40090b978eba) 7f60fedcc7724b897f5d233f50cf5f3228393047)

and If I commented this line, It works as before
```
  
   const scale = interpolate(logoAnimValue.value, [0, 1], [2, 1]);

    return {
      zIndex: 15,
      position: 'absolute',
      left,
      top,


      /// transform: [{scale}],

    };
  });
```

Is this new scale animation intended?

**Comment by hyochan** [comment]
> Might be related or not..
> latest version shows strange logo icon animation like belows.
> once it was scaled, it never goes back to small size..
> 
> 1. when logo pressed(touch)
>    ![Simulator Screen Recording - iPhone 12 Pro - 2021-07-27 at 22 25 14](https://user-images.githubusercontent.com/8540420/127162919-fef8f1b1-aeb7-4875-a5b2-e9e6e091faf0.gif)
> 2. when type begins in TextInput component
>    ![Simulator Screen Recording - iPhone 12 Pro - 2021-07-27 at 22 26 00](https://user-images.githubusercontent.com/8540420/127163448-7788a7d1-a0b3-46ce-a3c7-fc2b5279e122.gif)
> 
> It happens only after the [commit](https://github.com/dooboolab/hackatalk/pull/431/commits/331b7cdd770e60b68d52955a0a4d40090b978eba) [7f60fed](https://github.com/dooboolab/hackatalk/commit/7f60fedcc7724b897f5d233f50cf5f3228393047))
> 
> and If I commented this line, It works as before
> 
> ```
>   
>    const scale = interpolate(logoAnimValue.value, [0, 1], [2, 1]);
> 
>     return {
>       zIndex: 15,
>       position: 'absolute',
>       left,
>       top,
> 
> 
>       /// transform: [{scale}],
> 
>     };
>   });
> ```
> 
> Is this new scale animation intended?
> 
> Tested on:
> iPhone 12 Pro / iOS 14.5 simulator on Big Sur 11.4

Thank you so much for testing it out!

@DevYuns I think you might want to check this one!

**Comment by DevYuns** [comment]
Let me check it out soon! Thank you for reporting.
