### ISSUE TITLE
Status message could be overflowing text content area

### ISSUE THREAD

**Issue by imjlk** [dooboolab/hackatalk#455]
**Specify project**
Client & Server

**Describe the bug**
If status message is stored large length of text, it looks weird on the search user screen

**To Reproduce**
1. Create account and set status message long
2. Sign in with another account and go to 'User search' screen
3. Then you can see that status message is overflowing text content area
4. Click the user and also see with modal view.

**Expected behavior**
- Status message should have max length of character in server & client side

Unfortunately, i'm not familiar with graphql, so i could't find the implementation of validation about fields and schemas. if it has no validation, i think these types of bugs can also be found in other fields. (length of username, nickname, etc.)

**Screenshots**
![bug report](https://and.guide/wp-content/uploads/2021/08/2021-08-16_01h47_03.jpg)
![bug report](https://and.guide/wp-content/uploads/2021/08/2021-08-16_01h47_16.jpg)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: all of type
- Version: latest

**Comment by hyochan** [comment]
You can still contribute to this issue even if you are not familiar with graphql!

I think you can try to set the max number of lines and provide a restricted views.

**Comment by rarira** [comment]
Now I've tried to solve this issue... I think we should limit the maxLength of TextInput first and solve how to display possible preoccupied long status message. I'm trying the way just like Kakao Talk as below.. 

![Simulator Screen Recording - iPhone 12 Pro - 2021-08-17 at 10 56 21](https://user-images.githubusercontent.com/8540420/129651557-4156485f-9f09-40ed-a6fc-e3d694459f65.gif)

I will add arrow(up-down) button right side of the text if there are more text to show.
But it seems hard  to know if the text is ellipsized or not

**Comment by hyochan** [comment]
Updated in [1.9.0](https://github.com/dooboolab/hackatalk/releases/tag/1.9.0)
