### ISSUE TITLE
License Agreement Message is hidden in website.

### ISSUE THREAD

**Issue by SimYunSup** [dooboolab/hackatalk#458]
**Specify project**
Client - Website

**Describe the bug**
some of License Agreement Message is not appeared.

**To Reproduce**
Clear localstorage and Try Login. 

**Expected behavior**
All of License Agreement Message is appeared.

**Screenshots**
![image](https://user-images.githubusercontent.com/47362439/129864166-3c22ec3a-f493-4939-ae76-10fdf74044c0.png)
on Firefox
![image](https://user-images.githubusercontent.com/47362439/129864298-03409300-cc50-41ae-ad62-1b47a12cd399.png)
on Chrome

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Browser: Chrome 92, Firefox 91

[Wehack] - [we go]

**Comment by kty1965** [comment]
@hyochan

**Comment by kty1965** [comment]
@geoseong Please check this issue

**Comment by hyochan** [comment]
Above can be achieved easily by giving theme colors to `ScrollView`.

```
contentContainerStyle={{
  paddingVertical: 8,
  paddingHorizontal: 20,
  backgroundColor: theme.background,
}}>
```

![image](https://user-images.githubusercontent.com/27461460/130346273-bff7d417-1af9-4c54-86da-35f2b337d02a.png)

But this senario can just be removed in `web` and `android` since it is not actually needed!

**Comment by geoseong** [comment]
@SimYunSup 

I found why this happens,

key thing is the "flexbox" css props.

`align-items: center;` and `justify-content: center;` make this happen.

so commenting that props can fix the problem.

[src/components/pages/LicenseAgreement.tsx#L11](https://github.com/dooboolab/hackatalk/blob/master/client/src/components/pages/LicenseAgreement.tsx#L11)
```
const Container = styled.SafeAreaView`
  padding: 8px;

  flex: 1;
  flex-direction: row;
  align-items: center; // <-- comment this
  justify-content: center; // <-- comment this
`;
```

you can make this PR of this!

**Comment by hyochan** [comment]
> @SimYunSup
> 
> I found why this happens,
> 
> key thing is the "flexbox" css props.
> 
> `align-items: center;` and `justify-content: center;` make this happen.
> 
> so commenting that props can fix the problem.
> 
> [src/components/pages/LicenseAgreement.tsx#L11](https://github.com/dooboolab/hackatalk/blob/master/client/src/components/pages/LicenseAgreement.tsx#L11)
> 
> ```
> const Container = styled.SafeAreaView`
>   padding: 8px;
> 
>   flex: 1;
>   flex-direction: row;
>   align-items: center; // <-- comment this
>   justify-content: center; // <-- comment this
> `;
> ```
> 
> hopefully this helps!

Looks like a better fix~! Applied commit in the `PR`.
