### ISSUE TITLE
Create empty channel (Self Chat?)

### ISSUE THREAD

**Issue by imjlk** [dooboolab/hackatalk#459]
**Specify project**
Client

**Describe the bug**
When user create channel with not selecting other user,
channel is created but not showing on channel list.

**To Reproduce**
1. Go to channel screen and click plus button for creating new channel
2. Click `Done` button on right top 
3. You can see a new channel created without other user

**Expected behavior**
If there are no selected users, `Done` button would be disappeared

**Screenshots**
![issue-create-empty-channel](https://and.guide/wp-content/uploads/2021/08/issue-create-empty-channel-2.webp)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Tested on Chrome
- Version: latest

**Additional context**
When channel created with no selected user, there still remained messages.
I'm not sure, but i think these messages would be better to not store

**Comment by qkreltms** [comment]
Is it expected feature? @hyochan  or is it bug?

**Comment by hyochan** [comment]
@qkreltms Good point~! Maybe we can change ux accordingly? We need to observe what data we can use to differentiate this first.

**Comment by rarira** [comment]
I'm trying to solve this by checking `selectedUsers.length === 0`, and if true, `DONE` button will be disabled and its color should be changed to `theme.disabled` also..

I'll make PR on this change with Self Chat feature sooner or later
