### ISSUE TITLE
Delete same channel notification if enter the chat channel.

### ISSUE THREAD

**Issue by SimYunSup** [dooboolab/hackatalk#463]
**Specify project**
Client

**Is your feature request related to a problem? Please describe.**
Delete same channel notification if enter the chat channel.

https://user-images.githubusercontent.com/47362439/130353568-3920c141-fb42-45e6-8c5f-64239e0af1b6.mp4

**Describe alternatives you've considered**
Combine the notification which is same channel that like slack, or kakaotalk.

**Additional context**
I can't find notification trigger part on chat. I want to know where is the code that triggers notification.

**Comment by hyochan** [comment]
I've posted related issue in Expo earlier!! You might want to see here https://github.com/expo/expo/issues/11042.

I think still it is not possible using expo-notification :(

**Comment by SimYunSup** [comment]
How about first one? That "Delete same channel notification if enter the chat channel." one does not need collapse notification function. I'll try make disscussion for collapse notification on expo, but They don't seem to want to apply that function.

**Comment by hyochan** [comment]
The first approach looks great~!

**Comment by hyochan** [comment]
Closes via #476
