### ISSUE TITLE
Upload movie clip in [Message]

### ISSUE THREAD

**Issue by hyochan** [dooboolab/hackatalk#479]
**Specify project**
Both

**Is your feature request related to a problem? Please describe.**
Currently, we can only upload images. Add ability to add video clip up to 100mb.

**Describe the solution you'd like**
1. ~~Update the design for the inputs.~~
    <img width="211" alt="Screen Shot 2021-09-01 at 6 34 16 PM" src="https://user-images.githubusercontent.com/27461460/131648712-ba927430-368b-4331-a91b-da5ec6e862d6.png">
    - Done in https://github.com/dooboolab/hackatalk/pull/487
2. Upload the video clicking on the newly added input

**Comment by rarira** [comment]
I'm trying to introduce this feature....
but there is no proper icon for video upload, should I use `that clip icon`?
and by clicking the `camera` icon, we can also take video and upload it if we want to allow it but now we can just take still photo.

**Comment by 0916dhkim** [comment]
@rarira I think the gallery icon is the most intuitive one to use. It would be awesome if the camera icon can be used also.

**Comment by rarira** [comment]
> @rarira I think the gallery icon is the most intuitive one to use. It would be awesome if the camera icon can be used also.

The gallery icon is used to pick a still image only for now, and of course it can handle both image and video but I'm afraid it needs more refactoring... I'll try.

**Comment by 0916dhkim** [comment]
@rarira Thanks! Keep me updated with your progress :+1:
